export const GET_REFERENTIAL_PAYS_REQUEST = 'Vacancy/GET_REFERENTIAL_PAYS_REQUEST';
export const GET_REFERENTIAL_PAYS_SUCCES = 'Vacancy/GET_REFERENTIAL_PAYS_SUCCES';

export const GET_REFERENTIAL_CONTRACTS_REQUEST = 'Vacancy/GET_REFERENTIAL_CONTRACTS_REQUEST';
export const GET_REFERENTIAL_CONTRACTS_SUCCES = 'Vacancy/GET_REFERENTIAL_CONTRACTS_SUCCES';

export const GET_REFERENTIAL_SPECIALITE_REQUEST = 'Vacancy/GET_REFERENTIAL_SPECIALITE_REQUEST';
export const GET_REFERENTIAL_SPECIALITE_SUCCES = 'Vacancy/GET_REFERENTIAL_SPECIALITE_SUCCES';

export const GET_REFERENTIAL_FAILURE = 'Vacancy/GET_REFERENTIAL_FAILURE';