export const GET_REFERENTIAL_PAYS_REQUEST = 'Vacancy/GET_REFERENTIAL_PAYS_REQUEST';
export const GET_REFERENTIAL_PAYS_SUCCESS = 'Vacancy/GET_REFERENTIAL_PAYS_SUCCESS';

export const GET_REFERENTIAL_CONTRACTS_REQUEST = 'Vacancy/GET_REFERENTIAL_CONTRACTS_REQUEST';
export const GET_REFERENTIAL_CONTRACTS_SUCCESS = 'Vacancy/GET_REFERENTIAL_CONTRACTS_SUCCESS';

export const GET_REFERENTIAL_SPECIALITE_REQUEST = 'Vacancy/GET_REFERENTIAL_SPECIALITE_REQUEST';
export const GET_REFERENTIAL_SPECIALITE_SUCCESS = 'Vacancy/GET_REFERENTIAL_SPECIALITE_SUCCESS';

export const GET_REFERENTIAL_FAILURE = 'Vacancy/GET_REFERENTIAL_FAILURE';

export const GET_VACANCIES_TOP_REQUEST = 'Vacancy/GET_VACANCIES_TOP_REQUEST';
export const GET_VACANCIES_TOP_SUCCESS = 'Vacancy/GET_VACANCIES_TOP_SUCCESS';
export const GET_VACANCIES_TOP_FAILURE = 'Vacancy/GET_VACANCIES_TOP_FAILURE';

export const GET_VACANCIES_REQUEST = 'Vacancy/GET_VACANCIES_REQUEST';
export const GET_VACANCIES_SUCCESS = 'Vacancy/GET_VACANCIES_SUCCESS';
export const GET_VACANCIES_FAILURE = 'Vacancy/GET_VACANCIES_FAILURE';